optim:
  lr_init: 3e-4
  lr_min: 1e-5
  weight_decay: 1e-5

train:
  seed: 3047
  epochs: 15
  device: "gpu"
  save_dir: ''
  precision: 32
  resume: False
  v_num: -1

data:
  train:
    dir: "C:\\dataset\\UIEB\\train"
    img_size: 256
    batch_size: 4
  valid:
    dir: "C:\\dataset\\UIEB\\val"
    img_size: 256
    batch_size: 4
  test:
    dir: "C:\\dataset\\test_dateset\\original"
    img_size: 256
  num_works: 2
  pin_memory: True